### ISSUE TITLE
Crafting.

### ISSUE THREAD

**Issue by Botan626** [LiteOnE/Steam-Scripts#3]
It still crafts only 1 badge for a given game.

**Comment by LiteOnE** [comment]
Bug has been found and fixed. It was all because of GM_setValue, when the value is 0, GM_getValue returns undefined, so that it wasn't working properly and didn't continue crafting when badge have more than 1 level available

**Comment by Botan626** [comment]
I will give it a test on weekends.

**Comment by Botan626** [comment]
It still craftes only 1 badge for a game in the 1st run, but then it auto reloads the page and continues carfting.

I guess with that the issue is solved.

**Comment by LiteOnE** [comment]
Yep, It's supposed to craft only 1 level for 1 run. I believe It's more effective than parse every badge's page and check how many sets available to craft. But now I started to think that It'd be great to add this feature as an additional setting to let user decide what's better, so that I'll include it in the next update.

**Comment by Botan626** [comment]
It's even more effective taking into account the time needed to reload the badge page?

But for me, the process goes continuously until completiton, and I'm happy with that.
